capabilities:
  dns:
    zones:
      - domain: docker.internal
        authoritative: true
        records:
          - name: host
            type: CNAME
            value: host.bento.internal
  forward:
    enabled: true
    tcp:
      auto_discover: true
    uds:
      - name: docker
        guest_path: /var/run/docker.sock
        host_path: docker.sock
