[tracks.stable]
version = "6.19.7"
arch = "arm64"
config = "arm64-base"

[tracks.longterm]
version = "6.18.17"
arch = "arm64"
config = "arm64-base"

[tracks.longterm5]
version = "5.15.202"
arch = "arm64"
config = "arm64-base"
