FROM alpine:3.21.2

RUN apk add git \
        alpine-sdk \
        ncurses-dev \
        linux-headers \
        perl \
        curl

ARG VERSION=1.36.1
ENV VERSION=$VERSION

WORKDIR /build

RUN curl -L https://busybox.net/downloads/busybox-${VERSION}.tar.bz2 | tar -xvjf - --strip-components=1

COPY .config .

RUN make
